/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Alerta.java
 *
 * Created on 20/08/2008, 06:48:33 PM
 */

package omoikane.formularios;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Octavio
 */
public class Alerta extends JDialog {

    /** Creates new form Alerta */
    public Alerta(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        omoikane.sistema.Herramientas.panelAviso(this);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension labelSize = this.getPreferredSize();

        setLocation(screenSize.width/2 - (labelSize.width/2), screenSize.height/2 - (labelSize.height/2));
    }
    
        /*this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER , 0), "cerrar");
        this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cerrar");
        this.getRootPane().getActionMap().put("cerrar" , new adminAcciones(this));
    }

    class adminAcciones extends javax.swing.AbstractAction
    {
        JDialog dialogo;
        adminAcciones(JDialog dialogo)
        {
            this.dialogo = dialogo;
        }
        public void actionPerformed(ActionEvent ae)
        {
            this.dialogo.dispose();
        }
    }*/


    public void setMensaje(String mensaje)
    {
        String msjXLineas = "";
        int largo = 50, nLetrasLinea = 0;
        String[] palabras  = mensaje.split(" ");

        for(int i = 0; i < palabras.length; i++)
        {
            if(nLetrasLinea + palabras[i].length() <= largo)
            {
                nLetrasLinea += palabras[i].length();
                msjXLineas += " " + palabras[i];
            } else {
                nLetrasLinea = palabras[i].length();
                msjXLineas += "<br>" + palabras[i];
            }
        }
        this.txtAlerta.setText("<html>"+msjXLineas+"</html>");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlerta = new JLabel();
        btnAlerta = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alerta");

        txtAlerta.setIcon(new ImageIcon(getClass().getResource("/package-toys-128x128.png"))); // NOI18N
        txtAlerta.setText("Alerta");

        btnAlerta.setText("Aceptar");
        btnAlerta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnAlertaActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtAlerta, GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlerta, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnAlerta, GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(txtAlerta, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlertaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAlertaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAlertaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alerta dialog = new Alerta(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAlerta;
    private JLabel txtAlerta;
    // End of variables declaration//GEN-END:variables

}
