package omoikane.formularios;

import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import omoikane.sistema.*;

/*
 * @author Octavio
 */
public class Articulo extends JInternalFrame {

    BufferedImage fondo;
    public int ID;

    /**
     * Creates new form Articulo
     */
    public Articulo() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel) this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new JLabel();
        btnCerrar = new JButton();
        btnGuardar = new JButton();
        btnModificar = new JButton();
        jLabel13 = new JLabel();
        tabbedPane = new JTabbedPane();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        txtIDArticulo = new JTextField();
        jLabel3 = new JLabel();
        txtCodigo = new JTextField();
        jLabel8 = new JLabel();
        txtIDGrupoDes = new JTextField();
        jLabel4 = new JLabel();
        txtDescripcion = new JTextField();
        jLabel5 = new JLabel();
        txtUnidad = new JComboBox();
        txtPrecio = new JTextField();
        jLabel12 = new JLabel();
        jLabel7 = new JLabel();
        txtUModificacion = new JTextField();
        jPanel4 = new JPanel();
        jLabel19 = new JLabel();
        txtDescuento = new JTextField();
        txtIDGrupo = new JTextField();
        jLabel9 = new JLabel();
        txtIDLinea = new JTextField();
        txtIDLineaDes = new JTextField();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        tblCodigos = new JTable();
        btnAddCode = new JButton();
        btnDelCode = new JButton();
        jPanel5 = new JPanel();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        jLabel20 = new JLabel();
        jLabel6 = new JLabel();
        jLabel11 = new JLabel();
        jLabel21 = new JLabel();
        jLabel22 = new JLabel();
        jLabel24 = new JLabel();
        txtImpuestos = new JTextField();
        txtUtilidad = new JTextField();
        txtDescuento2 = new JTextField();
        jLabel25 = new JLabel();
        jLabel26 = new JLabel();
        jLabel27 = new JLabel();
        txtCosto = new JFormattedTextField();
        txtPrecioTotal = new JFormattedTextField();
        txtDesctoPorcentaje = new JFormattedTextField();
        txtImpuestosPorc = new JFormattedTextField();
        txtUtilidadPorc = new JFormattedTextField();
        jPanel7 = new JPanel();
        jScrollPane4 = new JScrollPane();
        txtComentarios = new JTextArea();

        setTitle("Producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("<html><head><style type='text/css'>body { font-family: 'Roboto Thin'; font-size: 28px; }</style></head>\n<body>\nArt&iacute;culo\n</body></html>"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 80, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 100, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 10, 10));

        jPanel1.setBackground(new Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new Color(204, 204, 204));
        jLabel1.setText("<html>ID Art&iacute;culo:</html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtIDArticulo.setEditable(false);
        txtIDArticulo.setBackground(new Color(51, 51, 51));
        txtIDArticulo.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        txtIDArticulo.setForeground(new Color(255, 255, 255));
        txtIDArticulo.setHorizontalAlignment(JTextField.RIGHT);
        txtIDArticulo.setBorder(null);
        txtIDArticulo.setFocusable(false);
        txtIDArticulo.setOpaque(false);
        jPanel1.add(txtIDArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 300, 30));

        jLabel3.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new Color(204, 204, 204));
        jLabel3.setText("<html>C&oacute;digo <br>principal:<html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 51, 300, 30));

        jLabel8.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new Color(204, 204, 204));
        jLabel8.setText("<html>ID L&iacute;nea [F1]:</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        txtIDGrupoDes.setEditable(false);
        txtIDGrupoDes.setBackground(new Color(51, 51, 51));
        txtIDGrupoDes.setForeground(new Color(255, 255, 255));
        txtIDGrupoDes.setBorder(null);
        txtIDGrupoDes.setFocusable(false);
        txtIDGrupoDes.setOpaque(false);
        jPanel1.add(txtIDGrupoDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 250, 30));

        jLabel4.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new Color(204, 204, 204));
        jLabel4.setText("<html>Descripci&oacute;n:</html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        txtDescripcion.setEditable(false);
        txtDescripcion.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 300, 30));

        jLabel5.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new Color(204, 204, 204));
        jLabel5.setText("Unidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 20));

        txtUnidad.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        txtUnidad.setModel(new DefaultComboBoxModel(new String[] { "PZA", "CAJA", "PAQ", "KG", "LT" }));
        txtUnidad.setEnabled(false);
        jPanel1.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 300, 30));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new Color(51, 51, 51));
        txtPrecio.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtPrecio.setForeground(new Color(255, 255, 255));
        txtPrecio.setHorizontalAlignment(JTextField.RIGHT);
        txtPrecio.setText("0.0");
        txtPrecio.setBorder(null);
        txtPrecio.setOpaque(false);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 300, 30));

        jLabel12.setFont(new Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new Color(204, 204, 204));
        jLabel12.setText("Precio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        jLabel7.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new Color(204, 204, 204));
        jLabel7.setText("<html>&Uacute;ltima<br>Modificaci&oacute;n:</html>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtUModificacion.setEditable(false);
        txtUModificacion.setBackground(new Color(51, 51, 51));
        txtUModificacion.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        txtUModificacion.setForeground(new Color(255, 255, 255));
        txtUModificacion.setHorizontalAlignment(JTextField.RIGHT);
        txtUModificacion.setText("Sin fecha");
        txtUModificacion.setBorder(null);
        txtUModificacion.setFocusable(false);
        txtUModificacion.setOpaque(false);
        jPanel1.add(txtUModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 300, 30));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -40, -1, 20));

        jLabel19.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new Color(204, 204, 204));
        jLabel19.setText("Descuento:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        txtDescuento.setEditable(false);
        txtDescuento.setBackground(new Color(51, 51, 51));
        txtDescuento.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtDescuento.setForeground(new Color(255, 255, 255));
        txtDescuento.setHorizontalAlignment(JTextField.RIGHT);
        txtDescuento.setText("0.0");
        txtDescuento.setBorder(null);
        txtDescuento.setOpaque(false);
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 300, 30));

        txtIDGrupo.setEditable(false);
        txtIDGrupo.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        txtIDGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDGrupoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, 30));

        jLabel9.setFont(new Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new Color(204, 204, 204));
        jLabel9.setText("ID Grupo [F1] :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 20));

        txtIDLinea.setEditable(false);
        txtIDLinea.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtIDLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 40, 30));

        txtIDLineaDes.setEditable(false);
        txtIDLineaDes.setBackground(new Color(51, 51, 51));
        txtIDLineaDes.setForeground(new Color(255, 255, 255));
        txtIDLineaDes.setBorder(null);
        txtIDLineaDes.setFocusable(false);
        txtIDLineaDes.setOpaque(false);
        jPanel1.add(txtIDLineaDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, 30));

        tabbedPane.addTab("<html>General</html>", jPanel1);

        jPanel2.setBackground(new Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html>C&oacute;digo</html>"
            }
        ));
        jScrollPane1.setViewportView(tblCodigos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 320));

        btnAddCode.setText("+");
        jPanel2.add(btnAddCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 40, 20));

        btnDelCode.setText("-");
        jPanel2.add(btnDelCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 20));

        tabbedPane.addTab("<html>C&oacute;digos</html>", jPanel2);

        jPanel5.setBackground(new Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new Color(255, 255, 255));
        jLabel15.setText("Impuestos (%):");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel16.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new Color(255, 255, 255));
        jLabel16.setText("Costo:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 30));

        jLabel17.setForeground(new Color(255, 255, 255));
        jLabel17.setText("Utilidad (%):");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jLabel18.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new Color(255, 255, 255));
        jLabel18.setText("Detalles del precio y costo");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new Color(255, 255, 255));
        jLabel20.setText("Precio:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 30));

        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("$:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 20));

        jLabel11.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setText("$");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 20, 30));

        jLabel21.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new Color(255, 255, 255));
        jLabel21.setText("$");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 20, 30));

        jLabel22.setForeground(new Color(255, 255, 255));
        jLabel22.setText("$:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 20));

        jLabel24.setForeground(new Color(255, 255, 255));
        jLabel24.setText("$:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 20));

        txtImpuestos.setEditable(false);
        txtImpuestos.setBackground(new Color(51, 51, 51));
        txtImpuestos.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtImpuestos.setForeground(new Color(255, 255, 255));
        txtImpuestos.setHorizontalAlignment(JTextField.CENTER);
        txtImpuestos.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        txtImpuestos.setFocusable(false);
        txtImpuestos.setOpaque(false);
        jPanel5.add(txtImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 110, 30));

        txtUtilidad.setEditable(false);
        txtUtilidad.setBackground(new Color(51, 51, 51));
        txtUtilidad.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtUtilidad.setForeground(new Color(255, 255, 255));
        txtUtilidad.setHorizontalAlignment(JTextField.CENTER);
        txtUtilidad.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        txtUtilidad.setFocusable(false);
        txtUtilidad.setOpaque(false);
        jPanel5.add(txtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 110, 30));

        txtDescuento2.setEditable(false);
        txtDescuento2.setBackground(new Color(51, 51, 51));
        txtDescuento2.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtDescuento2.setForeground(new Color(255, 255, 255));
        txtDescuento2.setHorizontalAlignment(JTextField.CENTER);
        txtDescuento2.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        txtDescuento2.setFocusable(false);
        txtDescuento2.setOpaque(false);
        jPanel5.add(txtDescuento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 110, 30));

        jLabel25.setForeground(new Color(255, 255, 255));
        jLabel25.setText("el precio siguiente no incluye los demas descuentos");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 340, 20));

        jLabel26.setForeground(new Color(255, 255, 255));
        jLabel26.setText("Descuento (%):");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel27.setForeground(new Color(255, 255, 255));
        jLabel27.setText("<html>Nota: El descuento que aparece es solo por art&iacute;culo  </html>");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 340, 20));

        txtCosto.setEditable(false);
        txtCosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCosto.setHorizontalAlignment(JTextField.CENTER);
        txtCosto.setToolTipText("Solo numeros");
        txtCosto.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtCosto.setHighlighter(null);
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCostoKeyReleased(evt);
            }
        });
        jPanel5.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 140, 30));

        txtPrecioTotal.setEditable(false);
        txtPrecioTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioTotal.setHorizontalAlignment(JTextField.CENTER);
        txtPrecioTotal.setToolTipText("Solo numeros");
        txtPrecioTotal.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtPrecioTotal.setHighlighter(null);
        txtPrecioTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioTotalKeyReleased(evt);
            }
        });
        jPanel5.add(txtPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, 30));

        txtDesctoPorcentaje.setEditable(false);
        txtDesctoPorcentaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtDesctoPorcentaje.setHorizontalAlignment(JTextField.CENTER);
        txtDesctoPorcentaje.setToolTipText("Solo numeros");
        txtDesctoPorcentaje.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtDesctoPorcentaje.setHighlighter(null);
        txtDesctoPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDesctoPorcentajeKeyReleased(evt);
            }
        });
        jPanel5.add(txtDesctoPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 30));

        txtImpuestosPorc.setEditable(false);
        txtImpuestosPorc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtImpuestosPorc.setHorizontalAlignment(JTextField.CENTER);
        txtImpuestosPorc.setToolTipText("Solo numeros");
        txtImpuestosPorc.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtImpuestosPorc.setHighlighter(null);
        txtImpuestosPorc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImpuestosPorcKeyReleased(evt);
            }
        });
        jPanel5.add(txtImpuestosPorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 30));

        txtUtilidadPorc.setEditable(false);
        txtUtilidadPorc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtUtilidadPorc.setHorizontalAlignment(JTextField.CENTER);
        txtUtilidadPorc.setToolTipText("Solo numeros");
        txtUtilidadPorc.setFont(new Font("Arial", 0, 14)); // NOI18N
        txtUtilidadPorc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUtilidadPorcKeyReleased(evt);
            }
        });
        jPanel5.add(txtUtilidadPorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 30));

        tabbedPane.addTab("<html>Precio</html>", jPanel5);

        jPanel7.setBackground(new Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setMaximumSize(new Dimension(32767, 200));
        jScrollPane4.setPreferredSize(new Dimension(406, 383));

        txtComentarios.setColumns(25);
        txtComentarios.setRows(20);
        txtComentarios.setMaximumSize(new Dimension(2147483647, 200));
        txtComentarios.setPreferredSize(new Dimension(404, 364));
        jScrollPane4.setViewportView(txtComentarios);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 350));

        tabbedPane.addTab("<html>Notas</html>", jPanel7);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 430, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.guardar(this);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.modificar(this);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtPrecioTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioTotalKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularUtilidad(this);
}//GEN-LAST:event_txtPrecioTotalKeyReleased

    private void txtDesctoPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesctoPorcentajeKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtDesctoPorcentajeKeyReleased

    private void txtImpuestosPorcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpuestosPorcKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtImpuestosPorcKeyReleased

    private void txtUtilidadPorcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadPorcKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtUtilidadPorcKeyReleased

    private void txtCostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtCostoKeyReleased

    private void txtIDGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDGrupoActionPerformed

    public void setEditable(boolean editable) {
        this.tblCodigos.setEnabled(editable);
        this.txtCodigo.setEditable(editable);
        this.txtComentarios.setEditable(editable);
        this.txtCosto.setEditable(editable);
        this.txtDescripcion.setEditable(editable);
        this.txtDesctoPorcentaje.setEditable(editable);
        this.txtDescuento2.setEditable(editable);
        this.txtIDGrupo.setEditable(editable);
        this.txtIDLinea.setEditable(editable);
        this.txtImpuestos.setEditable(editable);
        this.txtImpuestosPorc.setEditable(editable);
        this.txtPrecioTotal.setEditable(editable);
        this.txtUnidad.setEnabled(editable);
        this.txtUtilidad.setEditable(editable);
        this.txtUtilidadPorc.setEditable(editable);

    }

    public void setModoDetalles() {
        setModo(Modos.DETALLES);
        setEditable(false);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(false);

    }

    public void setModoModificar() {
        setModo(Modos.MODIFICAR);
        setEditable(true);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(true);
    }

    public void setModoNuevo() {
        setModo(Modos.NUEVO);
        setEditable(true);
        this.btnModificar.setVisible(false);
    }

    public enum Modos {

        NUEVO, DETALLES, MODIFICAR
    };
    private Modos modo;

    private void setModo(Modos m) {
        modo = m;
    }

    public Modos getModo() {
        return modo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAddCode;
    private JButton btnCerrar;
    private JButton btnDelCode;
    private JButton btnGuardar;
    private JButton btnModificar;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel7;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane4;
    public JTabbedPane tabbedPane;
    private JTable tblCodigos;
    private JTextField txtCodigo;
    private JTextArea txtComentarios;
    private JFormattedTextField txtCosto;
    private JTextField txtDescripcion;
    private JFormattedTextField txtDesctoPorcentaje;
    private JTextField txtDescuento;
    private JTextField txtDescuento2;
    private JTextField txtIDArticulo;
    public JTextField txtIDGrupo;
    public JTextField txtIDGrupoDes;
    public JTextField txtIDLinea;
    public JTextField txtIDLineaDes;
    private JTextField txtImpuestos;
    private JFormattedTextField txtImpuestosPorc;
    private JTextField txtPrecio;
    private JFormattedTextField txtPrecioTotal;
    private JTextField txtUModificacion;
    private JComboBox txtUnidad;
    private JTextField txtUtilidad;
    private JFormattedTextField txtUtilidadPorc;
    // End of variables declaration//GEN-END:variables

    public String getTxtCodigo() {
        return txtCodigo.getText();
    }

    public String getTxtDescripcion() {
        return txtDescripcion.getText();
    }

    public String getTxtIDArticulo() {
        return txtIDArticulo.getText();
    }

    public String getTxtUnidad() {
        return String.valueOf(txtUnidad.getSelectedItem());
    }

    public String getTxtUModificacion() {
        return txtUModificacion.getText();
    }

    public String getTxtIDLinea() {
        return txtIDLinea.getText();
    }

    public String getTxtIDGrupo() {
        return txtIDGrupo.getText();
    }

    public String getTxtDescuento() {
        return txtDescuento.getText();
    }

    public String getTxtCosto() {
        return txtCosto.getText();
    }

    public String getTxtPrecio() {
        return txtPrecio.getText();
    }

    public String getTxtComentarios() {
        return txtComentarios.getText();
    }

    public Component getIDLinea() {
        return txtIDLinea;
    }

    public Component getIDGrupo() {
        return txtIDGrupo;
    }

    public JTextField getTxtImpuestos() {
        return txtImpuestos;
    }

    public JTextField getCampoID() {
        return txtIDLinea;
    }

    public JTextField getCampoGrupo() {
        return txtIDGrupo;
    }

    public JTextField getTxtDesctoPorcentaje() {
        return txtDesctoPorcentaje;
    }

    public JTextField getTxtDescuento2() {
        return txtDescuento2;
    }

    public JTextField getTxtImpuestos3() {
        return txtImpuestos;
    }

    public JTextField getTxtImpuestosPorc() {
        return txtImpuestosPorc;
    }

    public JTextField getTxtPrecioTotal() {
        return txtPrecioTotal;
    }

    public JTextField getTxtUtilidadPorc() {
        return txtUtilidadPorc;
    }

    public JTextField getTxtUtilidad() {
        return txtUtilidad;
    }

    public void setTxtCodigo(String txtCodigo) {
        this.txtCodigo.setText(txtCodigo);
    }

    public void setTxtDescripcion(String txtDescripcion) {
        this.txtDescripcion.setText(txtDescripcion);
    }

    public void setTxtIDArticulo(String txtIDArticulo) {
        this.txtIDArticulo.setText(txtIDArticulo);
    }

    public void setTxtUnidad(String txt) {
        this.txtUnidad.setSelectedItem(txt);
    }

    public void setTxtUModificacion(String txt) {
        txtUModificacion.setText(txt);
    }

    public void setTxtIDLinea(String IDLinea) {
        txtIDLinea.setText(IDLinea);
    }

    public void setTxtIDGrupo(String IDGrupo) {
        txtIDGrupo.setText(IDGrupo);
    }

    public void setTxtIDLineaDes(String IDLinea) {
        txtIDLineaDes.setText(IDLinea);
    }

    public void setTxtIDGrupoDes(String IDGrupo) {
        txtIDGrupoDes.setText(IDGrupo);
    }

    public void setTxtDescuento(String descuento) {
        txtDescuento.setText(descuento);
    }

    public void setTxtCosto(String costo) {
        txtCosto.setText(costo);
    }

    public void setTxtPrecio(String precio) {
        this.txtPrecio.setText(precio);
    }

    public void setTxtPrecioTotal(String precio) {
        this.txtPrecioTotal.setText(precio);
    }

    public void setTxtImpuestos(String txt) {
        this.getTxtPrecioTotal().setText(txt);
    }

    public void setTxtDesctoPorcentaje(String txtDestoPorcentaje) {
        this.txtDesctoPorcentaje.setText(txtDestoPorcentaje);
    }

    public void setTxtDescuento2(JTextField txtDescuento2) {
        this.txtDescuento2 = txtDescuento2;
    }

    public void setTxtDescuento3(String descuento) {
        this.txtDescuento2.setText(descuento);
    }

    public void setTxtImpuestos3(JTextField txtImpuestos3) {
        this.txtImpuestos = txtImpuestos3;
    }

    public void setTxtImpuestos4(String txtImpuestos3) {
        this.txtImpuestos.setText(txtImpuestos3);
    }

    public void setTxtImpuestosPorc(String txtImpuestosPorc) {
        this.txtImpuestosPorc.setText(txtImpuestosPorc);
    }

    public void setTxtUtilidadPorc(String txtUtilidadPorc) {
        this.txtUtilidadPorc.setText(txtUtilidadPorc);
    }

    public void setTxtUtilidadPorcText(String txt) {
        txtUtilidadPorc.setText(txt);
    }

    public void setTxtUtilidad(JTextField txtUtilidad) {
        this.txtUtilidad = txtUtilidad;
    }

    public void setTxtUtilidad2(String utilidad) {
        this.txtUtilidad.setText(utilidad);
    }

    public void setTxtComentarios(String text) {
        txtComentarios.setText(text);
    }

    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(fondo, 0, 0, null);

    }

    public void generarFondo(Component componente) {
        Rectangle areaDibujo = this.getBounds();
        BufferedImage tmp;
        GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

        tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) tmp.getGraphics();
        g2d.setColor(new Color(0,0,0,165));
        g2d.fillRect(0, 0, areaDibujo.width, areaDibujo.height);
        fondo = tmp;
    }
}

/*
 costo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                costoCaretUpdate(evt);
            }
        });
*/