/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Caja.java
 * Created on 8/12/2008, 10:47:24 PM
 */

package omoikane.formularios;

import java.awt.image.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.table.*;

/*
 * @author Usuario
 */

public class Caja extends JInternalFrame {

    BufferedImage          fondo;
    DefaultTableModel      modelo;
    Double                 impuestos = 0.0;
    Double                 totalOriginal = 0.0;
    /** Creates new form Caja */

    public Caja() {
        initComponents();
        programarShortcuts();
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);
        modelo = (DefaultTableModel)this.tablaVenta.getModel();
        this.jLabel12.setVisible(false);
        this.jLabel13.setVisible(false);
    }

    public void programarShortcuts() {
        /*
            Herramientas.In2ActionX(form, KeyEvent.VK_F3    , "buscar"    ) { form.txtCaptura.requestFocusInWindow()  }
            Herramientas.In2ActionX(form, KeyEvent.VK_ESCAPE, "cerrar"    ) { form.btnCerrar.doClick()                }
            Herramientas.In2ActionX(form, KeyEvent.VK_F4    , "ventaEsp"  ) { form.btnVentaEspecial.doClick()         }
            Herramientas.In2ActionX(form, KeyEvent.VK_PAUSE , "pausar"    ) { form.btnPausar.doClick()                }
            Herramientas.In2ActionX(form, KeyEvent.VK_F12   , "cancelar"  ) { form.btnCancelacion.doClick()           }
            Herramientas.In2ActionX(form, KeyEvent.VK_F7    , "cancelaArt") { form.btnCancelaArt.doClick()            }
            Herramientas.In2ActionX(form, KeyEvent.VK_F5    , "movs"      ) { form.btnMovimientos.doClick()           }

         */
        Action buscar = new AbstractAction() { public void actionPerformed(ActionEvent e) { txtCaptura.requestFocusInWindow(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "buscar");
        getActionMap().put("buscar"                 , buscar  );

        Action cerrar = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnCerrar.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cerrar");
        getActionMap().put("cerrar", cerrar);

        Action ventaEsp = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnVentaEspecial.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "ventaEsp");
        getActionMap().put("ventaEsp" , ventaEsp);

        Action pausar = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnPausar.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_PAUSE, 0), "pausar");
        getActionMap().put("pausar" , pausar);

        Action cancelar = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnCancelacion.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "cancelar");
        getActionMap().put("cancelar", cancelar);

        Action cancelaArt = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnCancelaArt.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0), "cancelaArt");
        getActionMap().put("cancelaArt", cancelaArt);

        Action movs = new AbstractAction() { public void actionPerformed(ActionEvent e) { btnMovimientos.doClick(); } };
        getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "movs");
        getActionMap().put("movs"                 , movs  );
    }
    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,165));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }

    /* This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new JButton();
        txtCaja = new JLabel();
        jScrollPane1 = new JScrollPane();
        tablaVenta = new JTable();
        btnTerminar = new JButton();
        btnCatalogo = new JButton();
        btnCancelacion = new JButton();
        txtCaptura = new JTextField();
        jLabel4 = new JLabel();
        btnCancelaArt = new JButton();
        txtFecha = new JLabel();
        txtDescuento = new JLabel();
        btnMovimientos = new JButton();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel10 = new JLabel();
        txtNArticulos = new JLabel();
        jLabel16 = new JLabel();
        txtSubtotal = new JLabel();
        jLabel8 = new JLabel();
        txtTotal = new JLabel();
        jLabel9 = new JLabel();
        txtEfectivo = new JTextField();
        jLabel14 = new JLabel();
        txtCambio = new JTextField();
        btnPausar = new JButton();
        btnVentaEspecial = new JButton();
        jLabel17 = new JLabel();
        txtImpuesto = new JLabel();
        jLabel18 = new JLabel();

        setFocusable(false);
        setFrameIcon(new ImageIcon(getClass().getResource("/32x32/shopping_cart.png"))); // NOI18N
        setMaximumSize(new Dimension(1024, 768));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(1000, 600));
        setRequestFocusEnabled(false);

        btnCerrar.setFont(new Font("Arial", 0, 14));
        btnCerrar.setIcon(new ImageIcon(getClass().getResource("/32x32/back.png"))); // NOI18N
        btnCerrar.setText("Cerrar [Esc]");
        btnCerrar.setMargin(new Insets(2, 9, 2, 9));
        btnCerrar.setMaximumSize(new Dimension(250, 35));
        btnCerrar.setMinimumSize(new Dimension(200, 30));
        btnCerrar.setPreferredSize(new Dimension(200, 30));
        btnCerrar.setRequestFocusEnabled(false);

        txtCaja.setFont(new Font("Arial", 1, 36));
        txtCaja.setForeground(new Color(255, 255, 255));
        txtCaja.setText("Caja");
        txtCaja.setFocusable(false);

        tablaVenta.setFont(new Font("Arial", 0, 18));
        tablaVenta.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Artículo", "Concepto", "Cantidad", "Precio", "Descuento", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVenta.setFocusable(false);
        tablaVenta.setRowHeight(20);
        tablaVenta.setRowMargin(0);
        jScrollPane1.setViewportView(tablaVenta);

        btnTerminar.setFont(new Font("Arial", 0, 14));
        btnTerminar.setIcon(new ImageIcon(getClass().getResource("/32x32/accept.png"))); // NOI18N
        btnTerminar.setText("<html>Terminar Venta <br> [Enter]<html>");
        btnTerminar.setMargin(new Insets(2, 9, 2, 9));
        btnTerminar.setMaximumSize(new Dimension(250, 35));
        btnTerminar.setMinimumSize(new Dimension(200, 30));
        btnTerminar.setPreferredSize(new Dimension(200, 30));

        btnCatalogo.setFont(new Font("Arial", 0, 14));
        btnCatalogo.setIcon(new ImageIcon(getClass().getResource("/32x32/page_search.png"))); // NOI18N
        btnCatalogo.setText("Buscar Artículo [F1]");
        btnCatalogo.setMargin(new Insets(2, 9, 2, 9));
        btnCatalogo.setMaximumSize(new Dimension(250, 35));
        btnCatalogo.setMinimumSize(new Dimension(200, 30));
        btnCatalogo.setPreferredSize(new Dimension(200, 30));

        btnCancelacion.setFont(new Font("Arial", 0, 14));
        btnCancelacion.setIcon(new ImageIcon(getClass().getResource("/32x32/shopping_cart_remove.png"))); // NOI18N
        btnCancelacion.setText("Cancelar Venta [F12]");
        btnCancelacion.setMargin(new Insets(2, 9, 2, 9));
        btnCancelacion.setMaximumSize(new Dimension(250, 35));
        btnCancelacion.setMinimumSize(new Dimension(200, 30));
        btnCancelacion.setPreferredSize(new Dimension(200, 30));
        btnCancelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCancelacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new Font("Tahoma", 1, 14));
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("Captura [F3] :");
        jLabel4.setFocusable(false);

        btnCancelaArt.setFont(new Font("Arial", 0, 14));
        btnCancelaArt.setIcon(new ImageIcon(getClass().getResource("/32x32/remove.png"))); // NOI18N
        btnCancelaArt.setText("Cancelar Artículo [F7]");
        btnCancelaArt.setMargin(new Insets(2, 9, 2, 9));
        btnCancelaArt.setMaximumSize(new Dimension(250, 35));
        btnCancelaArt.setMinimumSize(new Dimension(200, 30));
        btnCancelaArt.setPreferredSize(new Dimension(200, 30));

        txtFecha.setBackground(new Color(153, 51, 0));
        txtFecha.setFont(new Font("Tahoma", 1, 24));
        txtFecha.setForeground(new Color(255, 255, 255));
        txtFecha.setFocusable(false);

        txtDescuento.setBackground(new Color(153, 51, 0));
        txtDescuento.setFont(new Font("Tahoma", 1, 24));
        txtDescuento.setForeground(new Color(255, 255, 255));
        txtDescuento.setHorizontalAlignment(SwingConstants.CENTER);
        txtDescuento.setText("$ 0.00");
        txtDescuento.setFocusable(false);

        btnMovimientos.setFont(new Font("Arial", 0, 14));
        btnMovimientos.setIcon(new ImageIcon(getClass().getResource("/32x32/attachment.png"))); // NOI18N
        btnMovimientos.setText("Movimientos Caja [F5]");
        btnMovimientos.setMargin(new Insets(2, 9, 2, 9));
        btnMovimientos.setMaximumSize(new Dimension(250, 35));
        btnMovimientos.setMinimumSize(new Dimension(200, 30));
        btnMovimientos.setPreferredSize(new Dimension(200, 30));

        jLabel12.setFont(new Font("Tahoma", 1, 12));
        jLabel12.setForeground(new Color(255, 255, 255));
        jLabel12.setText("Cliente");
        jLabel12.setMaximumSize(new Dimension(80, 10));
        jLabel12.setMinimumSize(new Dimension(80, 10));
        jLabel12.setPreferredSize(new Dimension(80, 10));

        jLabel13.setBackground(new Color(153, 51, 0));
        jLabel13.setFont(new Font("Tahoma", 1, 20));
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setText("Público en general");
        jLabel13.setFocusable(false);
        jLabel13.setMaximumSize(new Dimension(220, 25));
        jLabel13.setMinimumSize(new Dimension(190, 25));
        jLabel13.setPreferredSize(new Dimension(195, 25));

        jLabel10.setFont(new Font("Tahoma", 1, 12));
        jLabel10.setForeground(new Color(255, 255, 255));
        jLabel10.setText("Artículos");
        jLabel10.setMaximumSize(new Dimension(85, 12));
        jLabel10.setMinimumSize(new Dimension(80, 10));
        jLabel10.setPreferredSize(new Dimension(80, 10));

        txtNArticulos.setBackground(new Color(153, 51, 0));
        txtNArticulos.setFont(new Font("Tahoma", 1, 24));
        txtNArticulos.setForeground(new Color(255, 255, 255));
        txtNArticulos.setHorizontalAlignment(SwingConstants.CENTER);
        txtNArticulos.setText("0");
        txtNArticulos.setFocusable(false);
        txtNArticulos.setMaximumSize(new Dimension(220, 25));
        txtNArticulos.setMinimumSize(new Dimension(190, 25));
        txtNArticulos.setPreferredSize(new Dimension(195, 25));

        jLabel16.setFont(new Font("Tahoma", 1, 12));
        jLabel16.setForeground(new Color(255, 255, 255));
        jLabel16.setText("Subtotal");
        jLabel16.setMaximumSize(new Dimension(85, 12));
        jLabel16.setMinimumSize(new Dimension(80, 10));
        jLabel16.setPreferredSize(new Dimension(80, 10));

        txtSubtotal.setBackground(new Color(153, 51, 0));
        txtSubtotal.setFont(new Font("Tahoma", 1, 24));
        txtSubtotal.setForeground(new Color(255, 255, 255));
        txtSubtotal.setHorizontalAlignment(SwingConstants.CENTER);
        txtSubtotal.setText("$ 0.00");
        txtSubtotal.setFocusable(false);
        txtSubtotal.setMaximumSize(new Dimension(220, 25));
        txtSubtotal.setMinimumSize(new Dimension(190, 25));
        txtSubtotal.setPreferredSize(new Dimension(195, 25));

        jLabel8.setFont(new Font("Tahoma", 1, 12));
        jLabel8.setForeground(new Color(255, 255, 255));
        jLabel8.setText("Total");
        jLabel8.setMaximumSize(new Dimension(85, 12));
        jLabel8.setMinimumSize(new Dimension(80, 10));
        jLabel8.setPreferredSize(new Dimension(80, 10));

        txtTotal.setBackground(new Color(153, 51, 0));
        txtTotal.setFont(new Font("Arial", 1, 36));
        txtTotal.setForeground(new Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(SwingConstants.CENTER);
        txtTotal.setText("$ 0.00");
        txtTotal.setFocusable(false);
        txtTotal.setMaximumSize(new Dimension(190, 50));
        txtTotal.setMinimumSize(new Dimension(190, 50));
        txtTotal.setPreferredSize(new Dimension(190, 50));

        jLabel9.setFont(new Font("Tahoma", 1, 12));
        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setText("Efectivo");
        jLabel9.setMaximumSize(new Dimension(85, 12));
        jLabel9.setMinimumSize(new Dimension(80, 10));
        jLabel9.setPreferredSize(new Dimension(80, 10));

        txtEfectivo.setFont(new Font("Tahoma", 1, 24));
        txtEfectivo.setHorizontalAlignment(JTextField.CENTER);
        txtEfectivo.setBorder(null);
        txtEfectivo.setMaximumSize(new Dimension(220, 25));
        txtEfectivo.setMinimumSize(new Dimension(190, 25));
        txtEfectivo.setPreferredSize(new Dimension(195, 25));

        jLabel14.setFont(new Font("Tahoma", 1, 12));
        jLabel14.setForeground(new Color(255, 255, 255));
        jLabel14.setText("Cambio");
        jLabel14.setMaximumSize(new Dimension(85, 12));
        jLabel14.setMinimumSize(new Dimension(80, 10));
        jLabel14.setPreferredSize(new Dimension(80, 10));

        txtCambio.setEditable(false);
        txtCambio.setFont(new Font("Tahoma", 1, 24));
        txtCambio.setForeground(new Color(0, 102, 204));
        txtCambio.setHorizontalAlignment(JTextField.CENTER);
        txtCambio.setText("$ 0.00");
        txtCambio.setBorder(null);
        txtCambio.setMaximumSize(new Dimension(220, 25));
        txtCambio.setMinimumSize(new Dimension(190, 25));
        txtCambio.setPreferredSize(new Dimension(195, 25));

        btnPausar.setFont(new Font("Arial", 0, 14));
        btnPausar.setIcon(new ImageIcon(getClass().getResource("/32x32/pause.png"))); // NOI18N
        btnPausar.setText("Pausar [Pause]");
        btnPausar.setMargin(new Insets(2, 9, 2, 9));
        btnPausar.setMaximumSize(new Dimension(250, 35));
        btnPausar.setMinimumSize(new Dimension(200, 30));
        btnPausar.setPreferredSize(new Dimension(200, 30));

        btnVentaEspecial.setFont(new Font("Arial", 0, 14));
        btnVentaEspecial.setIcon(new ImageIcon(getClass().getResource("/32x32/favorite.png"))); // NOI18N
        btnVentaEspecial.setText("Venta Especial [F4]");
        btnVentaEspecial.setMargin(new Insets(2, 9, 2, 9));
        btnVentaEspecial.setMaximumSize(new Dimension(250, 35));
        btnVentaEspecial.setMinimumSize(new Dimension(200, 30));
        btnVentaEspecial.setPreferredSize(new Dimension(200, 30));

        jLabel17.setFont(new Font("Tahoma", 1, 12));
        jLabel17.setForeground(new Color(255, 255, 255));
        jLabel17.setText("+ Impuestos");
        jLabel17.setMaximumSize(new Dimension(85, 12));
        jLabel17.setMinimumSize(new Dimension(80, 10));
        jLabel17.setPreferredSize(new Dimension(80, 10));

        txtImpuesto.setBackground(new Color(153, 51, 0));
        txtImpuesto.setFont(new Font("Tahoma", 1, 24));
        txtImpuesto.setForeground(new Color(255, 255, 255));
        txtImpuesto.setHorizontalAlignment(SwingConstants.CENTER);
        txtImpuesto.setText("$ 0.00");
        txtImpuesto.setFocusable(false);
        txtImpuesto.setMaximumSize(new Dimension(220, 29));
        txtImpuesto.setMinimumSize(new Dimension(190, 25));
        txtImpuesto.setPreferredSize(new Dimension(195, 25));

        jLabel18.setFont(new Font("Tahoma", 1, 12));
        jLabel18.setForeground(new Color(255, 255, 255));
        jLabel18.setText("- Descuento");
        jLabel18.setMaximumSize(new Dimension(85, 12));
        jLabel18.setMinimumSize(new Dimension(80, 10));
        jLabel18.setPreferredSize(new Dimension(80, 10));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnTerminar, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(txtCaja)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuento, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImpuesto, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(txtNArticulos, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEfectivo, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCambio, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtFecha, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnCerrar, GroupLayout.PREFERRED_SIZE, 237, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCaptura, GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMovimientos, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(btnCatalogo, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPausar, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(btnVentaEspecial, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelacion, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(btnCancelaArt, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaja)
                    .addComponent(txtFecha, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCerrar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 391, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNArticulos, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuento, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImpuesto, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEfectivo, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCambio, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCaptura, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelaArt, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentaEspecial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMovimientos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelacion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPausar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(btnTerminar, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCatalogo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelacionActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCancelacionActionPerformed
        // TODO add your handling code here:
        this.btnCerrar.doClick();
    }//GEN-LAST:event_btnCancelacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancelaArt;
    private JButton btnCancelacion;
    public JButton btnCatalogo;
    private JButton btnCerrar;
    public JButton btnMovimientos;
    private JButton btnPausar;
    public JButton btnTerminar;
    public JButton btnVentaEspecial;
    private JLabel jLabel10;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel4;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    public JTable tablaVenta;
    private JLabel txtCaja;
    public JTextField txtCambio;
    public JTextField txtCaptura;
    private JLabel txtDescuento;
    public JTextField txtEfectivo;
    public JLabel txtFecha;
    private JLabel txtImpuesto;
    private JLabel txtNArticulos;
    private JLabel txtSubtotal;
    private JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

}
