/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CatalogoDual.java
 *
 * Created on 12/07/2009, 02:12:03 AM
 */
package omoikane.formularios;

import java.util.*;
import java.awt.event.*;
import java.awt.image.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.event.*;
import omoikane.sistema.*;
import omoikane.principal.*;


public class CatalogoDual extends JInternalFrame {

    BufferedImage     fondo;

    /** Creates new form CatalogoDual */
    public CatalogoDual() {
        initComponents();

        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaLineasDuales = new JLabel();
        btnCerrar = new JButton();
        etiquetaDuales = new JLabel();
        etiquetaNormales = new JLabel();
        btnADual = new JButton();
        btnANormal = new JButton();
        jScrollPane2 = new JScrollPane();
        listaDuales = new JList();
        jScrollPane1 = new JScrollPane();
        listaNormales = new JList();

        setTitle("Catálogo de Líneas Dual");

        etiquetaLineasDuales.setFont(new Font("Arial", 1, 36));
        etiquetaLineasDuales.setForeground(new Color(255, 255, 255));
        etiquetaLineasDuales.setText("Catálogo de Lineas 2");

        btnCerrar.setIcon(new ImageIcon(getClass().getResource("/48x48/back.png"))); // NOI18N
        btnCerrar.setText("Cerrar[ESC]");
        btnCerrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        etiquetaDuales.setFont(new Font("Tahoma", 1, 12));
        etiquetaDuales.setForeground(new Color(255, 255, 255));
        etiquetaDuales.setText("Líneas duales");

        etiquetaNormales.setFont(new Font("Tahoma", 1, 12));
        etiquetaNormales.setForeground(new Color(255, 255, 255));
        etiquetaNormales.setText("Líneas normales");

        btnADual.setText(">>");
        btnADual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnADualActionPerformed(evt);
            }
        });

        btnANormal.setText("<<");
        btnANormal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnANormalActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaDuales);

        jScrollPane1.setViewportView(listaNormales);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNormales)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 271, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btnANormal, GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(btnADual, GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaDuales)
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 278, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(etiquetaLineasDuales)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btnCerrar, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaLineasDuales)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaDuales)
                            .addComponent(etiquetaNormales))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnADual)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnANormal)))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        /*
        if(!modal){
            ((javax.swing.JInternalFrame)((omoikane.principal.MenuPrincipal)omoikane.principal.Principal.getMenuPrincipal()).getMenuPrincipal()).requestFocusInWindow();
        }
         */
}//GEN-LAST:event_btnCerrarActionPerformed

    private void btnANormalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnANormalActionPerformed
        LineasDuales.cambioLineaDualANormal();
}//GEN-LAST:event_btnANormalActionPerformed

    private void btnADualActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnADualActionPerformed
        LineasDuales.cambioLineaNormalADual();
    }//GEN-LAST:event_btnADualActionPerformed


    public JList getListaNormales() {
        return listaNormales;
    }

    public JList getListaDuales() {
        return listaDuales;
    }

    public Object[] getSeleccionNormales() {
        Object[] seleccion = listaNormales.getSelectedValues();
        System.out.println("Selección normal:" );
        for(int i = 0; i < seleccion.length ; i++)
            System.out.println(seleccion[i].toString());
        System.out.println("Fin de selección normal." );
        return seleccion;
    }

    public Object[] getSeleccionDuales() {
        Object[] seleccion = listaDuales.getSelectedValues();
        System.out.println("Selección dual:" );
        for(int i = 0; i < seleccion.length ; i++)
            System.out.println(seleccion[i].toString());
        System.out.println("Fin de selección dual." );
        return seleccion;
    }

    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }

    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,165));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnADual;
    private JButton btnANormal;
    private JButton btnCerrar;
    private JLabel etiquetaDuales;
    private JLabel etiquetaLineasDuales;
    private JLabel etiquetaNormales;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JList listaDuales;
    private JList listaNormales;
    // End of variables declaration//GEN-END:variables

}
