/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CorteSucursalDetalles.java
 *
 * Created on 28/02/2009, 09:04:31 PM
 */

package omoikane.formularios;

import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import omoikane.sistema.*;
/**
 *
 * @author Usuario
 */
public class CorteMovimientoDetalles extends JInternalFrame {

    BufferedImage fondo;
    /** Creates new form CorteSucursalDetalles */
    public CorteMovimientoDetalles() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new JButton();
        jLabel1 = new JLabel();
        txtTotal = new JLabel();
        jLabel3 = new JLabel();
        txtRetiros = new JLabel();
        jLabel5 = new JLabel();
        txtDepositos = new JLabel();
        jLabel7 = new JLabel();
        txtImpuestos = new JLabel();
        jLabel9 = new JLabel();
        txtSubtotal = new JLabel();
        jLabel11 = new JLabel();
        txtDescuentos = new JLabel();
        jLabel13 = new JLabel();
        txtVentas = new JLabel();
        jLabel15 = new JLabel();
        txtNVentas = new JLabel();
        jLabel14 = new JLabel();
        btnImprimir = new JButton();

        setTitle("Movimientos de Caja");

        btnAceptar.setText("Aceptar");

        jLabel1.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("Importe:");

        txtTotal.setBackground(new Color(0, 0, 0));
        txtTotal.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        txtTotal.setForeground(new Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(SwingConstants.RIGHT);
        txtTotal.setText("0.00");
        txtTotal.setOpaque(true);

        jLabel3.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setText("Fecha:");

        txtRetiros.setBackground(new Color(0, 0, 0));
        txtRetiros.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtRetiros.setForeground(new Color(255, 255, 255));
        txtRetiros.setHorizontalAlignment(SwingConstants.RIGHT);
        txtRetiros.setText("0.00");
        txtRetiros.setOpaque(true);

        jLabel5.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new Color(255, 255, 255));
        jLabel5.setText("Autorizado:");

        txtDepositos.setBackground(new Color(0, 0, 0));
        txtDepositos.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtDepositos.setForeground(new Color(255, 255, 255));
        txtDepositos.setHorizontalAlignment(SwingConstants.RIGHT);
        txtDepositos.setText("0.00");
        txtDepositos.setOpaque(true);

        jLabel7.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new Color(255, 255, 255));
        jLabel7.setText("Almacen:");

        txtImpuestos.setBackground(new Color(0, 0, 0));
        txtImpuestos.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtImpuestos.setForeground(new Color(255, 255, 255));
        txtImpuestos.setHorizontalAlignment(SwingConstants.RIGHT);
        txtImpuestos.setText("0.00");
        txtImpuestos.setOpaque(true);

        jLabel9.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setText("Cajero:");

        txtSubtotal.setBackground(new Color(0, 0, 0));
        txtSubtotal.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtSubtotal.setForeground(new Color(255, 255, 255));
        txtSubtotal.setHorizontalAlignment(SwingConstants.RIGHT);
        txtSubtotal.setText("0.00");
        txtSubtotal.setOpaque(true);

        jLabel11.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setText("Caja:");

        txtDescuentos.setBackground(new Color(0, 0, 0));
        txtDescuentos.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtDescuentos.setForeground(new Color(255, 255, 255));
        txtDescuentos.setHorizontalAlignment(SwingConstants.RIGHT);
        txtDescuentos.setText("0.00");
        txtDescuentos.setOpaque(true);

        jLabel13.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setText("Id de movimiento :");

        txtVentas.setBackground(new Color(0, 0, 0));
        txtVentas.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtVentas.setForeground(new Color(255, 255, 255));
        txtVentas.setHorizontalAlignment(SwingConstants.RIGHT);
        txtVentas.setText("0.00");
        txtVentas.setOpaque(true);

        jLabel15.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new Color(255, 255, 255));
        jLabel15.setText("<html><head><style type='text/css'>body { font-family: 'Roboto Thin'; font-size: 28px; }</style></head>\n<body>\nMovimientos de Caja\n</body></html>");

        txtNVentas.setBackground(new Color(0, 0, 0));
        txtNVentas.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        txtNVentas.setForeground(new Color(255, 255, 255));
        txtNVentas.setHorizontalAlignment(SwingConstants.RIGHT);
        txtNVentas.setText("0");
        txtNVentas.setOpaque(true);

        jLabel14.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new Color(255, 255, 255));
        jLabel14.setText("Tipo de movimiento :");

        btnImprimir.setText("Imprimir");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImpuestos, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txtDescuentos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSubtotal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDepositos, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRetiros, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVentas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNVentas, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNVentas))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVentas))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImpuestos)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentos)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepositos)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRetiros)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnImprimir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnAceptar;
    public JButton btnImprimir;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel7;
    private JLabel jLabel9;
    public JLabel txtDepositos;
    public JLabel txtDescuentos;
    public JLabel txtImpuestos;
    public JLabel txtNVentas;
    public JLabel txtRetiros;
    public JLabel txtSubtotal;
    public JLabel txtTotal;
    public JLabel txtVentas;
    // End of variables declaration//GEN-END:variables

    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(0,0,0,165));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }

    /**
     * @return the btnAceptar
     */
    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    /**
     * @param btnAceptar the btnAceptar to set
     */
    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    /**
     * @return the txtDescuentos
     */
    public JLabel getTxtDescuentos() {
        return txtDescuentos;
    }

    /**
     * @param txtDescuentos the txtDescuentos to set
     */
    public void setTxtDescuentos(JLabel txtDescuentos) {
        this.txtDescuentos = txtDescuentos;
    }

    /**
     * @return the txtImpuestos
     */
    public JLabel getTxtImpuestos() {
        return txtImpuestos;
    }

    /**
     * @param txtImpuestos the txtImpuestos to set
     */
    public void setTxtImpuestos(JLabel txtImpuestos) {
        this.txtImpuestos = txtImpuestos;
    }

    /**
     * @return the txtDepositos
     */
    public JLabel getTxtDepositos() {
        return txtDepositos;
    }

    /**
     * @param txtIngresos the txtDepositos to set
     */
    public void setTxtDepositos(JLabel txtIngresos) {
        this.txtDepositos = txtIngresos;
    }

    /**
     * @return the txtRetiros
     */
    public JLabel getTxtRetiros() {
        return txtRetiros;
    }

    /**
     * @param txtRetiros the txtRetiros to set
     */
    public void setTxtRetiros(JLabel txtRetiros) {
        this.txtRetiros = txtRetiros;
    }

    /**
     * @return the txtSubtotal
     */
    public JLabel getTxtSubtotal() {
        return txtSubtotal;
    }

    /**
     * @param txtSubtotal the txtSubtotal to set
     */
    public void setTxtSubtotal(JLabel txtSubtotal) {
        this.txtSubtotal = txtSubtotal;
    }

    /**
     * @return the txtTotal
     */
    public JLabel getTxtTotal() {
        return txtTotal;
    }

    /**
     * @param txtTotal the txtTotal to set
     */
    public void setTxtTotal(JLabel txtTotal) {
        this.txtTotal = txtTotal;
    }

    /**
     * @return the txtVentas
     */
    public JLabel getTxtVentas() {
        return txtVentas;
    }

    /**
     * @param txtVentas the txtVentas to set
     */
    public void setTxtVentas(JLabel txtVentas) {
        this.txtVentas = txtVentas;
    }

    /**
     * @return the txtNVentas
     */
    public JLabel getTxtNVentas() {
        return txtNVentas;
    }

    /**
     * @param txtNVentas the txtNVentas to set
     */
    public void setTxtNVentas(JLabel txtNVentas) {
        this.txtNVentas = txtNVentas;
    }
}
